### ISSUE TITLE
Broken links to viewdocs.io in README.md files

### ISSUE THREAD

**Issue by renoirb** [radial/docs#4]
As described on [viewdocs.io](http://progrium.viewdocs.io/viewdocs/) site, the link in [the README.md of _radial/wheel-nginx_](https://raw.githubusercontent.com/radial/wheel-nginx/master/README.md) points to this repository (`radial/docs`) but expects a `docs/` folder with Markdown files which aren’t present.

Thought you’d want to know :)

**Comment by clemtibs** [comment]
Appreciated! I stopped using viewdocs.io and that was leftover. It's fixed in another unpublished branch. Thanks.
